### ISSUE TITLE
M statistic of 0 triggers a flag

### ISSUE THREAD

**Issue by kdpenner** [vrodgom/statmorph#1]
Hello,
I'm using the package to determine morphological parameters of sometimes "single clump" sources.  For these sources, the code sets the M statistic to 0 and triggers a flag.  This behavior is problematic for inspecting the quality of the other statistics.

**Comment by vrodgom** [comment]
I agree. This is something I considered before.

I just modified the code accordingly, so I'm closing this issue. If necessary, the user can still discard M=0 cases in postprocessing.

**Comment by kdpenner** [comment]
Thanks for addressing this quickly.  I still have a problem---perhaps unrelated---in _segmap_mid.  The same object for which M=0 has a MID segmap that is equal to the input segmap, which triggers a flag.

**Comment by vrodgom** [comment]
Just to make sure, are you getting a warning that says "[segmap_mid] Using original segmap"?

**Comment by kdpenner** [comment]
Yes.

**Comment by vrodgom** [comment]
Yes, the MID segmap is sometimes technically undefined, but I agree that perhaps this should not trigger the "bad measurement" flag. I just made a change that reflects this. In those cases the code now uses the Gini segmap for the MID calculations. Thanks for the feedback.
