### ISSUE TITLE
Offset of center for the fitted Sersic profile

### ISSUE THREAD

**Issue by oxno2** [vrodgom/statmorph#4]
Hello, I tired to run your turtorial code and reproduce the results. I found that there is an offset between the original image and  fitted image, as the image shows below.
![download](https://user-images.githubusercontent.com/22302177/50521999-46bdfa00-0a8e-11e9-95bd-bc4f1cf20eb8.png)
If I applied the code below, just moved the center. Then it would looks better.
```
morph.sersic_xc = morph.sersic_xc - 0.5
morph.sersic_yc = morph.sersic_yc - 0.5
```

![d2](https://user-images.githubusercontent.com/22302177/50522077-b2a06280-0a8e-11e9-93ee-92fcb21e1c60.png)

My system environment is Anaconda 3.7.1

**Comment by oxno2** [comment]
I tried to use Python 3.5.2 and reinstalled the lowest versions of required packages and seems this problem can be fixed.

**Comment by oxno2** [comment]
The sersic residual image shows some offset feature.

![d3](https://user-images.githubusercontent.com/22302177/50524620-707e1d80-0a9c-11e9-861c-e622a0d0334e.png)

**Comment by vrodgom** [comment]
Hi. I noticed this a couple of months ago and it should already be fixed in the GitHub version (see commits from Oct. 22, 2018), but the changes have not made it to an official release yet, which is what actually gets installed via Anaconda. I will probably release statmorph v0.3.3 next week. Thanks!

**Comment by oxno2** [comment]
Thank you very much. I have replaced the python code and solved this problem.

I have an addittional question. For an images with multiple sources, photutils.detect_sources can find them all. However, the order of these sources are based on their luminosities. I am studying some very dim sources which lies at the middle of the image. Is there any methods for me to put the center source to the first one?  I want to run a for loop for many different images.

**Comment by vrodgom** [comment]
Great. I'll mark this as solved.

About your other question, if you are sure that there should be a source at the center of the image, then it should be straightforward to obtain its "label". For example, if you create a segmentation map (`segm`) as described in the [tutorial](https://nbviewer.jupyter.org/github/vrodgom/statmorph/blob/master/notebooks/tutorial.ipynb), then the label of the source at the center can be obtained as follows:

```
ny, nx = segm.data.shape
ic, jc = ny//2, nx//2
label = segm.data[ic, jc]
assert label > 0
```

If `label == 0`, then the source was not detected (a value of zero is reserved for the background), so you should either skip the image, lower the detection threshold, or use a more sophisticated source detection tool (e.g. SExtractor).
